# Generated by Django 5.1.1 on 2024-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(upload_to="event_thumbnails/"),
        ),
    ]
