# Generated by Django 5.1.1 on 2024-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="manage_code",
            field=models.CharField(default="xK6HSmLLt9", max_length=12, unique=True),
        ),
    ]
