# Generated by Django 5.1.1 on 2024-09-29 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_registration_manage_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="manage_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
