# Generated by Django 5.1.1 on 2024-09-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_remove_user_created_at_remove_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="user",
        ),
        migrations.AddField(
            model_name="registration",
            name="client_email",
            field=models.EmailField(default="test", max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
