# Generated by Django 5.1.1 on 2024-09-30 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="events.user",
            ),
            preserve_default=False,
        ),
    ]
