# Generated by Django 5.1.1 on 2024-09-30 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_registration_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="user",
        ),
    ]
